[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "blobfish"
dynamic = ["version"]
description = "Python binary helper"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name = "Jack Huey" }
]
dependencies = []

[tool.setuptools_scm]